### ISSUE TITLE
Move to sbt-typelevel-site

### ISSUE THREAD

**Issue by milessabin** [typelevel/grackle#419]
Split off from #194.

**Comment by armanbilge** [comment]
I started looking at this a while back. The main thing blocking this migration is that Laika (used by sbt-typelevel-site) doesn't currently support "`@@snip`". Other Typelevel projects typically use mdoc when they want compiled examples in the documentation.

https://github.com/gemini-hlsw/gsp-graphql/blob/f2f3618b54f3c482646d2647dca9f8ffee106d8e/docs/src/main/paradox/tutorial/in-memory-model.md?plain=1#L146

Adding this feature to Laika would be a non-trivial enhancement.
- https://github.com/typelevel/Laika/issues/305

We could possibly find some other way to embed these, since they are hosted on GitHub. Or we could just use ordinary links. Or we could change the documentation to use ordinary codeblocks (possibly with mdoc) instead of embedding examples like this.

**Comment by milessabin** [comment]
I'm quite happy moving to Laika with ordinary codeblocks.

**Comment by milessabin** [comment]
Done in #494.
